const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name=session-token]').content;
const dimensions={story:'剧情',art:'美术与场景',system:'系统',polish:'打磨'};
const states={pending_confirmation:'待确认',not_started:'未开始',in_progress:'进行中',implemented_unverified:'实现完成待验证',done:'已完成'};
const reasons={implementation:'实现推进',regression:'缺陷回退',verification:'人工验收',demo_expansion:'范围变化',rule_change:'规则变化',manual_score_update:'手动评分',refinement:'目标细化',initial_baseline:'首次基线',future:'后续计划'};
let state,bundle,page='todos',dimension='all',status='all',scope='demo',draftRevision=0,baseRevision,saveTimer,saveChain=Promise.resolve(),savedJSON='',editSubmit,confirmation;
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(text,fn,cls)=>{const e=node('button',text,cls);e.type='button';e.addEventListener('click',fn);return e;};
const lines=s=>s.split('\n').map(s=>s.trim()).filter(Boolean);
const id=prefix=>prefix+'.'+crypto.randomUUID().replaceAll('-','');
const titleFor=x=>bundle.todo.items.find(t=>t.id===x)?.title||x;
function error(e){$('error').hidden=false;$('error').textContent=e.message||String(e);}
function clearError(){$('error').hidden=true;}
async function api(path,data){const response=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Session-Token':token},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'请求失败');return result;}
const request=()=>({base_revision:baseRevision,draft_revision:draftRevision,bundle:structuredClone(bundle)});
function changed(){clearError();$('apply').disabled=true;$('validation').hidden=true;$('save-status').textContent='草稿有变更，正在保存…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist().catch(error),400);}
function persist(){clearTimeout(saveTimer);saveChain=saveChain.catch(()=>{}).then(async()=>{const json=JSON.stringify(bundle);if(json===savedJSON)return;const result=await api('draft',request());draftRevision=result.draft_revision;savedJSON=json;$('save-status').textContent='草稿已保存 · 正式网站未改变';});return saveChain;}
async function load(){clearTimeout(saveTimer);$('apply').disabled=true;$('validation').hidden=true;state=await api('state');baseRevision=state.draft?.base_revision||state.base_revision;draftRevision=state.draft?.draft_revision||0;bundle=structuredClone(state.draft?.bundle||state.official);savedJSON=JSON.stringify(bundle);$('save-status').textContent=state.draft?'已恢复本地草稿':'当前为正式数据 · 尚无草稿';if(baseRevision!==state.base_revision)error(new Error('正式文件已有变化。请导出草稿后丢弃或重新载入，不会覆盖外部修改。'));$('change-type').value=bundle.change.type;$('change-reason').value=bundle.change.reason;render();}
function field(parent,label,value,options={}){const wrap=node('label',label),input=node(options.multiline?'textarea':options.choices?'select':'input');if(options.choices){if(options.multiple)input.multiple=true;for(const [v,text] of options.choices){const option=node('option',text);option.value=v;option.selected=options.multiple?value.includes(v):String(value??'')===v;input.append(option);}}else {if(input.tagName==='INPUT')input.type=options.type||'text';input.value=value??'';if(options.readonly)input.readOnly=true;if(options.type==='number'){input.step='any';if(options.min!==undefined)input.min=options.min;if(options.max!==undefined)input.max=options.max;}}
 wrap.append(input);if(options.hint)wrap.append(node('span',options.hint,'hint'));parent.append(wrap);if(options.change)input.addEventListener('input',()=>{options.change(options.multiple?[...input.selectedOptions].map(o=>o.value):input.value);changed();});return ()=>options.multiple?[...input.selectedOptions].map(o=>o.value):input.value;}
function confirmAction(title,text,fn){$('confirm-title').textContent=title;$('confirm-text').textContent=text;confirmation=fn;$('confirm').showModal();}
$('confirm-no').onclick=()=>$('confirm').close();$('confirm-yes').onclick=async()=>{$('confirm').close();try{await confirmation();}catch(e){error(e);}};
function openEditor(title,build,submit){$('editor-title').textContent=title;$('editor-fields').replaceChildren();$('editor-error').textContent='';const getters=build($('editor-fields'));editSubmit=()=>submit(getters);$('editor').showModal();}
$('close-editor').onclick=()=>$('editor').close();$('editor-form').onsubmit=e=>{e.preventDefault();try{editSubmit();$('editor').close();changed();render();}catch(err){$('editor-error').textContent=err.message;}};
function badge(value){return node('span',states[value||'pending_confirmation'],'badge '+(value||'pending_confirmation'));}
function render(){const root=$('workspace');root.replaceChildren();for(const b of document.querySelectorAll('[data-page]')){if(b.dataset.page===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}({todos:renderTodos,scores:renderScores,evaluation:renderEvaluation,content:renderContent,rules:renderRules,records:renderRecords})[page](root);}
for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>{page=b.dataset.page;render();};
$('change-type').onchange=e=>{bundle.change.type=e.target.value;changed();};$('change-reason').oninput=e=>{bundle.change.reason=e.target.value;changed();};
function references(ids){const found=[];for(const key of ['candidate_notes','pending_decisions'])for(const r of bundle.todo[key])if(r.related_ids.some(x=>ids.includes(x)))found.push(r.id+'（'+key+'）');return found;}
function deleteItem(item){const ids=[item.id,...bundle.todo.items.filter(t=>t.parent_id===item.id).map(t=>t.id)];const refs=references(ids);if(refs.length){error(new Error('请先解除或替换以下引用：\n'+refs.join('\n')));return;}confirmAction('移入回收站',`将删除 ${ids.length} 个条目。共享证据保留，应用后可从回收站恢复。`,()=>{const items=bundle.todo.items.filter(t=>ids.includes(t.id));const budgets=Object.fromEntries(ids.filter(i=>Object.hasOwn(bundle.todo.group_budgets,i)).map(i=>[i,bundle.todo.group_budgets[i]]));bundle.trash.push({id:id('trash'),deleted_at:new Date().toISOString(),items,budgets});bundle.todo.items=bundle.todo.items.filter(t=>!ids.includes(t.id));for(const i of ids)delete bundle.todo.group_budgets[i];changed();render();});}
function restoreTrash(entry){const ids=new Set(bundle.todo.items.map(t=>t.id));if(entry.items.some(t=>ids.has(t.id)))throw new Error('ID 已存在，不能覆盖恢复');for(const t of entry.items)if(t.parent_id&&!ids.has(t.parent_id)&&!entry.items.some(x=>x.id===t.parent_id))throw new Error('原所属大项不存在，请先恢复该大项');bundle.todo.items.push(...structuredClone(entry.items));Object.assign(bundle.todo.group_budgets,entry.budgets);bundle.trash=bundle.trash.filter(t=>t.id!==entry.id);changed();render();}
const expandedGroups=new Set();
const completedLast=(a,b)=>Number(a.status==='done')-Number(b.status==='done');
function aggregate(children){if(children.every(t=>t.status==='done'))return'done';if(children.every(t=>t.status==='not_started'))return'not_started';if(children.every(t=>t.status==='implemented_unverified'))return'implemented_unverified';if(children.some(t=>['in_progress','implemented_unverified','done'].includes(t.status)))return'in_progress';return null;}
function renderTodos(root){root.append(node('h2','Todo 管理'));const tabs=node('div',undefined,'dimensions');for(const [d,title] of [['all','全部维度'],...Object.entries(dimensions).filter(([d])=>d!=='polish')]){const b=button(title,()=>{dimension=d;status='all';scope='demo';render();});b.setAttribute('aria-pressed',String(d===dimension));tabs.append(b);}root.append(tabs);const filters=node('div',undefined,'form-grid');field(filters,'状态',status,{choices:[['all','全部状态'],...Object.entries(states)],change:v=>{status=v;render();}});field(filters,'范围',scope,{choices:[['demo','Demo 全部任务'],['future','后续计划'],['all','全部范围']],change:v=>{scope=v;render();}});root.append(filters);const actions=node('div',undefined,'actions');actions.append(button('新增大项',()=>editGroup()),button('管理证据',()=>editRecords('evidence')),button('管理验收计划',()=>editRecords('verification_plans')),button('管理关联事项',editAssociations));root.append(actions);
 const groups=bundle.todo.items.filter(t=>t.kind==='group').map(g=>({...g,children:bundle.todo.items.filter(t=>t.parent_id===g.id)})).sort((a,b)=>Number(aggregate(a.children)==='done')-Number(aggregate(b.children)==='done'));
 let count=0;for(const g of groups){if(dimension!=='all'&&g.dimension!==dimension||scope!=='all'&&g.scope!==scope)continue;const children=g.children.filter(t=>status==='all'||(t.status||'pending_confirmation')===status).sort(completedLast);if(!children.length&&g.children.length)continue;count++;const card=node('details',undefined,'group');card.open=expandedGroups.has(g.id);const summary=node('summary');const head=node('div',undefined,'group-heading');const chevron=node('span','›','group-chevron');chevron.setAttribute('aria-hidden','true');summary.append(chevron);head.append(node('strong',g.title),node('span',`${dimensions[g.dimension]} · ${g.scope==='demo'?'Demo':'后续计划'} · ${g.children.length} 子项`,'subtitle'));const expandLabel=node('span',card.open?'收起子项':'展开子项','expand-label');const summaryEnd=node('div',undefined,'group-summary-end');summaryEnd.append(badge(aggregate(g.children)),expandLabel);summary.append(head,summaryEnd);card.addEventListener('toggle',()=>{if(!card.isConnected)return;if(card.open)expandedGroups.add(g.id);else expandedGroups.delete(g.id);expandLabel.textContent=card.open?'收起子项':'展开子项';});card.append(summary);const sum=g.children.reduce((n,t)=>n+Number(t.weight),0),budget=bundle.todo.group_budgets[g.id];card.append(node('p',`预算 ${budget} · 子项合计 ${sum} · 差额 ${Math.round((budget-sum)*1e8)/1e8}`,'budget'+(Math.abs(sum-budget)>1e-8?' bad':'')));const tools=node('div',undefined,'actions');tools.append(button('编辑大项／预算',()=>editGroup(g)),button('新增子项',()=>editTask(null,g)),button('删除大项',()=>deleteItem(g),'danger'));card.append(tools);for(const t of children){const row=node('div',undefined,'task todo-child');const top=node('div',undefined,'task-head');top.append(node('strong',t.title),badge(t.status));row.append(top,node('p',`权重 ${t.weight} · ${t.implementation_location==='main'?'主分支':t.implementation_location==='feature_branch'?'功能分支':'实现位置待确认'} · ${t.id}`,'small'),node('p',t.completion_criteria.join('\n')));const controls=node('div',undefined,'actions');controls.append(button('编辑任务',()=>editTask(t,g)),button('删除',()=>deleteItem(t),'danger'));row.append(controls);card.append(row);}root.append(card);}if(!count)root.append(node('p','当前筛选下没有任务。','empty'));
 const trash=node('details',undefined,'card');trash.append(node('summary',`回收站（${bundle.trash.length} 批）`));for(const entry of bundle.trash){const line=node('div',undefined,'task');line.append(node('p',entry.items.map(t=>t.title).join('、')),button('恢复到草稿',()=>{try{restoreTrash(entry);}catch(e){error(e);}}));trash.append(line);}root.append(trash);}
function blank(kind,parent){return {id:id(kind),parent_id:parent?.id||null,kind,title:'',dimension:parent?.dimension||'story',scope:parent?.scope||'demo',weight:kind==='task'?1:null,status:null,assessment:kind==='task'?'pending_confirmation':'aggregate',completion_criteria:[],evidence_ids:[],verification_ids:[],implementation_location:null,notes:''};}
function editGroup(item){openEditor(item?'编辑大项':'新增大项（同时创建首个子项）',p=>{const g=item||blank('group');p.append(node('p',g.id,'readonly'));return {g,title:field(p,'标题',g.title),dimension:field(p,'维度',g.dimension,{choices:Object.entries(dimensions).filter(([d])=>d!=='polish')}),scope:field(p,'范围',g.scope,{choices:[['demo','Demo'],['future','后续计划']]}),budget:field(p,'大项权重预算',item?bundle.todo.group_budgets[g.id]:1,{type:'number',min:0.000001,hint:'不会自动调整子项权重，应用前必须与子项合计相等。'}),notes:field(p,'备注',g.notes,{multiline:true}),childTitle:!item?field(p,'首个子项标题',''):null,criteria:!item?field(p,'首个子项完成条件（一行一条）','',{multiline:true}):null};},v=>{if(!v.title().trim()||!Number.isFinite(Number(v.budget()))||Number(v.budget())<=0)throw new Error('标题和有效正数预算必填');const g={...v.g,title:v.title().trim(),dimension:v.dimension(),scope:v.scope(),notes:v.notes()};if(item){Object.assign(item,g);for(const t of bundle.todo.items.filter(t=>t.parent_id===g.id)){t.dimension=g.dimension;t.scope=g.scope;}}else {if(!v.childTitle().trim()||!lines(v.criteria()).length)throw new Error('首个子项标题和完成条件必填');const t=blank('task',g);t.title=v.childTitle().trim();t.completion_criteria=lines(v.criteria());t.weight=Number(v.budget());bundle.todo.items.push(g,t);}bundle.todo.group_budgets[g.id]=Number(v.budget());});}
function editTask(item,parent){openEditor(item?'编辑任务':'新增子项',p=>{const t=item||blank('task',parent);p.append(node('p',t.id,'readonly'));const g={t,title:field(p,'标题',t.title),parent:field(p,'所属大项',t.parent_id,{choices:bundle.todo.items.filter(x=>x.kind==='group').map(x=>[x.id,`${x.title} / ${dimensions[x.dimension]} / ${x.scope}`]),hint:'移动后继承目标大项的维度与范围；其他子项不会移动。'}),status:field(p,'状态',t.status||'pending_confirmation',{choices:Object.entries(states)}),weight:field(p,'相对权重',t.weight,{type:'number',min:0.000001}),location:field(p,'实现位置',t.implementation_location||'',{choices:[['','待确认'],['main','主分支'],['feature_branch','功能分支']]}),criteria:field(p,'完成条件（一行一条）',t.completion_criteria.join('\n'),{multiline:true}),notes:field(p,'备注',t.notes,{multiline:true}),evidence:field(p,'证据（可多选）',t.evidence_ids,{multiple:true,choices:bundle.todo.evidence.map(x=>[x.id,x.summary])}),plans:field(p,'验收计划（可多选）',t.verification_ids,{multiple:true,choices:bundle.todo.verification_plans.map(x=>[x.id,x.title])})};const v=bundle.verifications[t.id]||{};g.note=field(p,'本次人工验收说明',v.note||'',{multiline:true,hint:'新标为已完成、修改已完成任务的条件或分支时必填。确认实际验收结果，不会运行游戏。'});g.source=field(p,'验收适用来源基线',v.source||bundle.todo.project.target_source,{choices:bundle.todo.sources.filter(s=>s.kind==='git').map(s=>[s.id,`${s.ref} · ${s.commit.slice(0,7)}`])});return g;},v=>{const target=bundle.todo.items.find(x=>x.id===v.parent());const weight=Number(v.weight());if(!v.title().trim()||!lines(v.criteria()).length||!Number.isFinite(weight)||weight<=0)throw new Error('标题、完成条件和有效正数权重必填');const s=v.status()==='pending_confirmation'?null:v.status();const t={...v.t,title:v.title().trim(),parent_id:target.id,dimension:target.dimension,scope:target.scope,status:s,assessment:s===null?'pending_confirmation':'assessed',weight,implementation_location:v.location()||null,completion_criteria:lines(v.criteria()),notes:v.notes(),evidence_ids:v.evidence(),verification_ids:v.plans()};bundle.verifications[t.id]={note:v.note(),source:v.source(),location:t.implementation_location};if(item)Object.assign(item,t);else bundle.todo.items.push(t);});}
function editRecords(key){openEditor(key==='evidence'?'证据管理':'人工验收计划管理',p=>{const records=structuredClone(bundle.todo[key]);const list=node('div');p.append(node('p','来源使用现有提交或目标文档基线；证据路径为仓库相对路径。已引用的记录不能删除。'));p.append(list);function draw(){list.replaceChildren();for(const r of records){const box=node('div',undefined,'card');box.append(node('p',r.id,'readonly'));field(box,key==='evidence'?'说明':'标题',key==='evidence'?r.summary:r.title,{multiline:key==='evidence',change:v=>{r[key==='evidence'?'summary':'title']=v;}});field(box,'来源',r.source,{choices:bundle.todo.sources.map(s=>[s.id,s.ref||s.path]),change:v=>r.source=v});if(key==='evidence'){field(box,'类型',r.kind,{choices:[['static_review','静态证据'],['document','文档'],['user_verification','用户验收']],change:v=>r.kind=v});field(box,'相对路径（一行一条）',r.paths.join('\n'),{multiline:true,change:v=>r.paths=lines(v)});}else {field(box,'步骤（一行一条）',r.steps.join('\n'),{multiline:true,change:v=>r.steps=lines(v)});field(box,'预期结果（一行一条）',r.expected.join('\n'),{multiline:true,change:v=>r.expected=lines(v)});field(box,'实际结果',r.result||'',{choices:[['','待验收'],['passed','通过'],['failed','失败']],change:v=>r.result=v||null});field(box,'验收记录（一行一条，填写日期和结果说明）',r.evidence.join('\n'),{multiline:true,change:v=>r.evidence=lines(v)});}box.append(button('删除记录',()=>{if(bundle.todo.items.some(t=>(key==='evidence'?t.evidence_ids:t.verification_ids).includes(r.id))){$('editor-error').textContent='该记录已被任务引用，先编辑任务解除引用。';return;}records.splice(records.indexOf(r),1);draw();},'danger'));list.append(box);}list.append(button('新增记录',()=>{records.push(key==='evidence'?{id:id('E'),source:bundle.todo.project.target_source,kind:'static_review',paths:[],summary:''}:{id:id('V'),source:bundle.todo.project.target_source,title:'',executor:'user',steps:[],expected:[],result:null,evidence:[]});draw();}));}draw();return records;},records=>{bundle.todo[key]=records;});}
function renderScores(root){root.append(node('h2','评分与验收'));for(const [key,s] of Object.entries(bundle.todo.manual_scores)){const box=node('div',undefined,'card');box.append(node('h3',titleFor(key)));field(box,'手动完成度（0—100；留空表示未知）',s.value,{type:'number',min:0,max:100,change:v=>s.value=v.trim()===''?null:Number(v)});field(box,'本次评分来源说明',bundle.manual_notes[key]||'',{multiline:true,change:v=>bundle.manual_notes[key]=v});box.append(node('p',`已记录来源时间：${s.updated_at||'未知'}；新的来源时间将在应用时记录。`,'small'));root.append(box);}root.append(button('管理人工验收计划',()=>editRecords('verification_plans')),node('p','任务标为已完成时，在 Todo 编辑窗口填写验收说明并选择实际验收分支。'));}
function evaluationLocation(parent, text, page) {
  const location=node('p',undefined,'evaluation-location');
  location.append(node('span',text));
  const link=node('a','查看对应页面 ↗');
  link.href='/preview/'+page+'.html';link.target='_blank';link.rel='noopener';
  location.append(link);parent.append(location);
}
function renderEvaluation(root) {
  const e=bundle.todo.evaluation;
  root.append(node('h2','评估内容'),node('p','按网站展示位置编辑本次评估文案。这里的文字不参与分数计算；页面标题、介绍和计算说明请到“网站文案”编辑。','evaluation-help'));

  const updates=node('section',undefined,'card evaluation-section');
  updates.append(node('h3','最近更新页面 · 主要成果'));
  evaluationLocation(updates,'显示位置：最近更新 → 本次评估 → 成果列表','updates');
  field(updates,'主要成果列表（一行一条）',e.highlights.join('\n'),{
    multiline:true,hint:'每一行对应网站中的一条编号成果，也显示在历史记录的“查看本次成果与评估基线”中。',
    change:v=>e.highlights=lines(v)
  });
  root.append(updates);

  const changes=node('section',undefined,'card evaluation-section');
  changes.append(node('h3','最近更新页面 · 变化原因'));
  evaluationLocation(changes,'显示位置：最近更新 → 本次口径与变化；历史记录 → 每次评估的摘要','updates');
  changes.append(node('p','原因类型用于归类记录，网站展示的是对应的说明文字。','small'));
  e.change_reasons.forEach((r,index)=>{
    const row=node('div',undefined,'evaluation-reason');
    row.append(node('h4',`变化原因 ${index+1}`));
    field(row,'原因类型',r.type,{choices:Object.entries(reasons),change:v=>r.type=v});
    field(row,'网站显示的原因说明',r.text,{multiline:true,change:v=>r.text=v});
    row.append(button('移除该原因',()=>{e.change_reasons.splice(e.change_reasons.indexOf(r),1);changed();render();}));
    changes.append(row);
  });
  changes.append(button('增加变化原因',()=>{e.change_reasons.push({type:'implementation',text:''});changed();render();}));
  root.append(changes);

  const reviews=node('section',undefined,'card evaluation-section');
  reviews.append(node('h3','维度进度页面 · 四个维度的评价'));
  evaluationLocation(reviews,'显示位置：维度进度 → 对应维度卡片 → 进度条和整体贡献下方的评价正文','dimensions');
  const reviewGrid=node('div',undefined,'evaluation-review-grid');
  for(const [d,title] of Object.entries(dimensions)) {
    const card=node('div',undefined,'evaluation-review');
    card.append(node('h4',title+'卡片'));
    field(card,title+'卡片的评价正文',e.dimension_reviews[d],{
      multiline:true,hint:`仅对应${title}维度的评价，不改动完成度、权重、贡献或剩余任务。`,
      change:v=>e.dimension_reviews[d]=v
    });
    reviewGrid.append(card);
  }
  reviews.append(reviewGrid);root.append(reviews);

  const history=node('section',undefined,'card evaluation-section');
  history.append(node('h3','历史记录页面 · 自动保留'));
  evaluationLocation(history,'显示位置：历史记录 → 每次评估的变化摘要及可展开的成果列表','history');
  history.append(node('p','历史页面复用上面的“主要成果”和“变化原因”，无需单独填写。应用形成新快照时保存本次内容；这里的编辑不会改写已有历史记录。'),node('p','四维度评价保存在快照中，评价正文显示在“维度进度”页面。评估时间由应用流程记录。','small'));
  root.append(history);
}

const copyLabels={'dimensions-title':'维度页栏目标题','updates-title':'最近更新栏目标题','todos-title':'任务列表标题','history-title':'历史栏目标题','method-title':'计算说明栏目标题','method-weight-title':'权重说明标题','method-status-title':'验收说明标题','method-weight-note':'权重说明','method-status-note':'状态与验收说明','method-limit-note':'评估限制说明','todo-note':'Todo 列表提示','empty':'筛选空状态提示','loading':'加载提示','error-title':'加载错误标题','retry':'重试按钮','footer-note':'页脚说明','method-note':'总进度来源说明'};
function renderContent(root){root.append(node('h2','网站文案'));field(root,'网站标题',bundle.config.title,{change:v=>bundle.config.title=v});field(root,'阶段标签',bundle.config.phase_label,{change:v=>bundle.config.phase_label=v});for(const [p,c] of Object.entries(bundle.content.pages)){const box=node('details',undefined,'card');box.append(node('summary',`${p} · ${c.title}`));field(box,'页面与导航标题',c.title,{change:v=>c.title=v});field(box,'页面介绍',c.intro,{multiline:true,change:v=>c.intro=v});root.append(box);}const other=node('details',undefined,'card');other.append(node('summary','计算说明与主要提示'));for(const [k,v] of Object.entries(bundle.content.text))field(other,copyLabels[k]||k,v,{multiline:true,change:value=>bundle.content.text[k]=value});root.append(other,node('p','以上内容作为纯文本显示。评分比例与计算结果仍由数据生成。'));}
function renderRules(root){root.append(node('h2','评分规则'),node('p','维度比例合计必须为100%；UI占比须大于0且小于100%。状态档位保持递增，未开始为0%，已完成为100%。'));const r=bundle.todo.rules;for(const [d,v] of Object.entries(r.dimension_shares))field(root,dimensions[d]+'占整体（%）',v*100,{type:'number',min:0,max:100,change:value=>r.dimension_shares[d]=Number(value)/100});field(root,'UI 占美术维度（%）',r.art_ui_share*100,{type:'number',min:0,max:100,change:v=>r.art_ui_share=Number(v)/100});for(const [k,v] of Object.entries(r.status_factors))field(root,states[k]+'档位（%）',v*100,{type:'number',min:0,max:100,change:value=>r.status_factors[k]=Number(value)/100});field(root,'规则状态',r.approval,{choices:[['confirmed','已确认'],['draft','草案']],change:v=>r.approval=v});root.append(node('p',`当前规则版本：${bundle.todo.snapshot.rules_version}。变化应用后自动生成新版本。`));}
function renderRecords(root){root.append(node('h2','应用记录'));if(!state.records.length)root.append(node('p','尚无本地管理工具应用记录。','empty'));for(const r of [...state.records].reverse()){const box=node('div',undefined,'card');box.append(node('h3',r.time),node('p',r.summary),node('p',`${r.new_snapshot?'生成新评估':'未新增评估'} · ${r.snapshot_id}`,'readonly'),button('恢复该次应用前的数据到草稿',()=>confirmAction('恢复旧数据到草稿','恢复 Todo 与网站文案，替换当前草稿。历史快照保留；仍需校验并应用。',async()=>{await persist();await api('restore',{...request(),id:r.id});await load();})));root.append(box);}}
function displayValidation(result){const root=$('validation-result');root.replaceChildren();root.append(node('p',result.new_snapshot?'校验通过：应用后将生成一次新评估。':'校验通过：无需新增进度历史。'));if(result.scope_warning)root.append(node('p','Demo 范围发生变化，请同步维护 Demo目标.md。','danger'));const comparison=node('div',undefined,'comparison');const value=v=>v===null?'待完善':v.toFixed(1)+'%';for(const [key,title] of [['before','正式数据'],['after','草稿计算']]){const box=node('div',undefined,'card');box.append(node('h3',title),node('p','整体：'+value(result[key].overall)));for(const d of result[key].dimensions)box.append(node('p',`${d.label}：${value(d.score)} · 整体贡献 ${d.contribution===null?'待确认':d.contribution.toFixed(1)+' 个百分点'}`));comparison.append(box);}root.append(comparison);const a=node('a','打开草稿网站预览 ↗');a.href=result.preview_url;a.target='_blank';a.rel='noopener';root.append(a);const list=node('div',undefined,'scroll-panel');for(const change of result.diff){const row=node('div',undefined,'diff');row.append(node('strong',change.field),node('pre','原值：'+JSON.stringify(change.before,null,2)),node('pre','新值：'+JSON.stringify(change.after,null,2)));list.append(row);}root.append(node('h3',`变更字段（${result.diff.length}）`),list);$('validation').hidden=false;$('apply').disabled=false;}
$('validate').onclick=async()=>{try{clearError();await persist();const result=await api('validate',request());displayValidation(result);}catch(e){error(e);$('apply').disabled=true;}};
$('apply').onclick=()=>confirmAction('应用到本地网站','将统一保存正式数据与网站并创建备份。不会提交、推送或公开发布。',async()=>{await persist();const result=await api('apply',request());await load();$('validation').hidden=true;$('apply').disabled=true;$('save-status').textContent=`已应用 · ${result.record.snapshot_id} · ${result.record.new_snapshot?'新增一次评估':'历史未增加'}`;});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(request(),null,2)],{type:'application/json'});const a=node('a');a.href=URL.createObjectURL(blob);a.download='devprogress-draft.json';a.click();URL.revokeObjectURL(a.href);};
$('reload').onclick=()=>confirmAction('重新载入','重新读取正式数据和已保存草稿。未保存的编辑可能丢失；冲突草稿可先导出。',load);
$('discard').onclick=()=>confirmAction('丢弃草稿','丢弃所有尚未应用的编辑，保留正式文件。',async()=>{clearTimeout(saveTimer);await saveChain.catch(()=>{});const current=await api('state');await api('discard',{base_revision:current.base_revision,draft_revision:draftRevision});await load();$('validation').hidden=true;$('apply').disabled=true;});
window.addEventListener('beforeunload',e=>{if(JSON.stringify(bundle)!==savedJSON){e.preventDefault();e.returnValue='';}});
load().catch(error);

function editAssociations(){openEditor('关联事项与待定设计',p=>{const sections={candidate_notes:structuredClone(bundle.todo.candidate_notes),pending_decisions:structuredClone(bundle.todo.pending_decisions)};for(const [key,records] of Object.entries(sections)){p.append(node('h3',key==='candidate_notes'?'候选事项':'待定设计'));for(const r of records){const box=node('div',undefined,'card');box.append(node('p',r.id,'readonly'));field(box,key==='candidate_notes'?'说明':'问题',r.note||r.question,{multiline:true,change:v=>r[key==='candidate_notes'?'note':'question']=v});field(box,'关联任务（可多选或清空）',r.related_ids,{multiple:true,choices:bundle.todo.items.map(t=>[t.id,t.title]),change:v=>r.related_ids=v});p.append(box);}}return sections;},sections=>Object.assign(bundle.todo,sections));}
